### ISSUE TITLE
add a web page to a tab

### ISSUE THREAD

**Issue by darkbluemsu** [Esri/map-series-storytelling-template-js#10]
When adding a web page to tab, it works fine on desktop browsers. When you open the app on iPhone, and navigate the tab, the web page will "leak through" the swiping bar. The swiping bar which is supposed to be locked at the bottom of the page actually scrolls with the content. An example I tried is to add www.esri.com to a tab. It looks fine on desktop, but looks strange on my iPhone (iPhone 5, Chrome, and Safari)

**Comment by glazou** [comment]
Thanks for the feedback, this can be fixed through a css rule:
`
#contentPanel {
  -webkit-overflow-scrolling: touch;
}
`

I will fix this in ArcGIS Online with next release around mid November. You can fix it earlier by deploying the application on your own server and adding that fix in index.html, see the following documentation https://github.com/Esri/map-series-storytelling-template-js#instructions and https://github.com/Esri/map-series-storytelling-template-js#other-customization
