### ISSUE TITLE
avoid login  when the map series is in my  own server.

### ISSUE THREAD

**Issue by sdlmedioambiente** [Esri/map-series-storytelling-template-js#15]
I uploaded the application to my own server. When someone tries to access through the address,
For example http://myurlcompany/mapseries/index.html,   they need  logging. I need public access to aplication
![loginesri](https://cloud.githubusercontent.com/assets/15903848/11235623/43d62604-8dd3-11e5-93e8-c9734e83f94b.jpg)

Can you  help me ?. I read something in the instructions but do not understand.  Can  you give me  more clearly  the steps?

Thanks a lot

**Comment by oevans** [comment]
Hi -- you will need to share the ArcGIS Online maps and layers used in your story with Everyone. Log in to arcgis.com, go to My Content, find select the maps/layers in your story, click Share, select Everyone.

Also, in the future please use our [GeoNet community page](https://geonet.esri.com/community/gis/web-gis/storymaps) for questions like this and reserve Github for software bugs/enhancements. Thanks!

Let me know if this helps.
Owen

**Comment by sdlmedioambiente** [comment]
Works fine ! thanks a lot.
Sorry for ask a quiesrtion in a wrong place.
 Regards

**Comment by oevans** [comment]
No problem. Glad that worked for you! You can also easily share all your story's maps/layers from the Share dialog in the app or from [My Stories on the Story Maps website](http://storymaps.arcgis.com/en/my-stories/).
