### ISSUE TITLE
Showing funny icons on mobile devices

### ISSUE THREAD

**Issue by darkbluemsu** [Esri/map-series-storytelling-template-js#22]
We are seeing funny icons in the following maps when viewing them on iphone and android phone
[http://maps.calgary.ca/StreetSweeping](http://maps.calgary.ca/StreetSweeping)
[http://maps.calgary.ca/spring](http://maps.calgary.ca/spring)
There are a hand icon in front of the title, and a burger icon in front of the swiping instruction. Also the close button in pop up windows is showing as a golf (or boat?) icon.
It's not very consistent. May take a few times of refreshing before you see them. Confirmed on 3 devices.

**Comment by glazou** [comment]
Sounds like the web font that is used to create those icons did not load properly.

I loaded the app over wifi like 20 times on Nexus 5 / Android 6 / Chrome and can't reproduce.

The font is distributed from the following folder: http://thecityofcalgary.maps.arcgis.com/apps/MapSeries/resources/lib/bootstrap/fonts/
There is multiple formats, recent smartphone would use the .woff2 http://thecityofcalgary.maps.arcgis.com/apps/MapSeries/resources/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2

Can you reproduce over wifi or only in 3/4G?

Font loading should not be an issue, I think you will have to plug your phone to a computer to look at the network calls and see if a file fail to load. That may be an issue with your web server.

See documentation https://developer.chrome.com/devtools/docs/remote-debugging http://moduscreate.com/enable-remote-web-inspector-in-ios-6/

**Comment by darkbluemsu** [comment]
I am using iPhone 6. I can see the funny icons in both Chrome and Safari, wifi and 3G. I was told maps are fine on a Samsung device. So the issue may be mostly related to iPhone?    Here is the screenshots
I don’t have a Mac, so can’t really troubleshoot.  Thank  you for your quick response.


Thanks

Michael Su
ISC: Protected

**Comment by darkbluemsu** [comment]
Turns out it is our own code that cause the issue. Close this now.

**Comment by oevans** [comment]
OK, thx for the update @darkbluemsu

**Comment by carmat** [comment]
Any chance you could enlighten us as to the code issue you had?

Having a similar issue whereby icon-font glyphs display fin over a WiFi network, but horribly on a 4G network connection. When inspecting the CSS in each case, the `content` value changes, again depending on the connection type.

**Wifi**
![wifi](https://cloud.githubusercontent.com/assets/1105267/24857695/1f513766-1de1-11e7-88a8-a69bdbe236e1.png)

![wifi-css](https://cloud.githubusercontent.com/assets/1105267/24857838/9754958c-1de1-11e7-80b6-6aef855c0271.png)

**4G**
![4g](https://cloud.githubusercontent.com/assets/1105267/24857696/1f58dade-1de1-11e7-92d8-b1cdb92d7966.png)

![4g-css](https://cloud.githubusercontent.com/assets/1105267/24857837/9751a8e0-1de1-11e7-8d3e-077c10d848b6.png)

Anyone got any guidance?
