### ISSUE TITLE
Printing tool inside Map serie

### ISSUE THREAD

**Issue by FoicikRemi** [Esri/map-series-storytelling-template-js#26]
Hi !

I would to know if is it possible to integrate a print Button on this app. This question is maybe stupid but I'm not a developers :/ 

Thanks you in advance

Best regards.

**Comment by oevans** [comment]
Hi -- Thanks for your feedback! For new feature requests please go to the [ArcGIS Ideas space on GeoNet](https://geonet.esri.com/community/arcgis-ideas/) to register your support for specific ideas. There is already an existing idea for adding printing to story maps you can vote for [here](https://geonet.esri.com/ideas/11153).

**Comment by oevans** [comment]
@FoicikRemi -- Also, when you vote it would also be helpful if you could please post a comment and let us know any details of how you'd like the print feature to work. Would the print button print all the tabs or just the current one? What would the layout of the printed document look like? Would it print the initial extent of any maps or the current extent if the person using the app has navigated the map?
