### ISSUE TITLE
Adding a tab externally

### ISSUE THREAD

**Issue by sarojthapa60** [Esri/map-series-storytelling-template-js#29]
I built an app using map series. It has 9 tabs. I have an application developed using php and sql server database table. I want to add my php application as an additional tab to the map series. How can I accomplish that? Thanks.

**Comment by oevans** [comment]
You should be able to just paste in the URL of your PHP app using the "web page" content type in a new section of your Map Series. Can you please try that if you haven't already and let me know if it works?

![2016-09-13 at 11 06 58 am](https://cloud.githubusercontent.com/assets/3215530/18479225/3791cb94-79a2-11e6-9cf5-ddba51fd39f1.JPG)

**Comment by sarojthapa60** [comment]
I am going to host my php app through our web server. After that, I should be able to embed it like you said. I will let you know if it works or not.Thanks

**Comment by sarojthapa60** [comment]
@oevans, That works. Thank you.
