### ISSUE TITLE
Pop-up are not positioned properly

### ISSUE THREAD

**Issue by glazou** [Esri/map-series-storytelling-template-js#5]
Reported on GeoNet https://geonet.esri.com/thread/127300

**Comment by jonoogle** [comment]
I think the problem is in setPopupPosition (Mainstage.js ) around line 981. It bases the position on the current position of the infoWindow and not where the new popup will be.

**Comment by glazou** [comment]
Thanks!
Not sure how I missed this but yes looks like that placement is done too early...
I remember struggling developing this, I think I need to find another way to get the event from the API, this can't be just delayed to accommodate Feature Service query that may take a while.

**Comment by jonoogle** [comment]
That's what I figured and I played around with it a bit but didn't find an easy solution, but I don't have a good handle on all of the things happening in the code. thanks for looking at it.

**Comment by glazou** [comment]
That's often tricky but thanks for looking! There must be a way, stay tuned :)

**Comment by jonoogle** [comment]
I think actually this bug was fixed. I had found a solution but then looked at the code in git, and around line 640 of MainStage.js you commented out the "selection-change" event and used "aspect-after" which seems to work fine.

**Comment by davidasbury** [comment]
This may be related to the above:

Popup up anchor moves relative to point feature.

When zooming, sometimes the popup stays in the same place relative to the browser window, but moves relative to the point it's referencing. See the sequence of screenshots below at consecutive zoom levels. May be related to the fact that the initial anchor is located just above the referenced point, though it ends up towards the left of the point at larger scales.

From: http://arcg.is/1zyiYmE

![uboat1](https://cloud.githubusercontent.com/assets/6776067/7522863/ca5aeffe-f4ac-11e4-9fc3-5a88ee767208.png)
![uboat2](https://cloud.githubusercontent.com/assets/6776067/7522864/ca5ea068-f4ac-11e4-99e8-957d667fedb0.png)
![uboat3](https://cloud.githubusercontent.com/assets/6776067/7522865/ca62a5c8-f4ac-11e4-80c0-a20336e37805.png)
![uboat4](https://cloud.githubusercontent.com/assets/6776067/7522866/ca6481fe-f4ac-11e4-96c4-80ca087f266d.png)

**Comment by glazou** [comment]
This was indeed fixed in a previous release, just that the app was not up-to-date.
