### ISSUE TITLE
Update built app

### ISSUE THREAD

**Issue by ccrozek** [Esri/map-series-storytelling-template-js#53]
Would it be possible to update the download for the built app to the latest version (below the picture in the readme)? It still says 1.14. I'm struggling to follow the instructions to build it myself from the full download.

**Comment by oevans** [comment]
@ccrozek -- The current version (1.27.0) of the built app is available on [this repo's Releases page](https://github.com/Esri/storymap-series/releases). 

My guess is you were trying to download the built app from the [Map Series page on the classic website](https://storymaps-classic.arcgis.com/en/app-list/map-series/). That site is no longer maintained. It will be taken down in the near future. For more information, see [this announcement](https://community.esri.com/t5/arcgis-storymaps-blog/retirement-of-classic-esri-story-maps-website/ba-p/1134062).

**Comment by ccrozek** [comment]
Thanks! I didn't realize those were different files on the release page as they kept trying to download with the same name and overwriting the last. Got it now after I renamed the downloads. I was originally trying to download it from the "Download" link below the picture in the README here on GitHub.

**Comment by oevans** [comment]
Thanks for that info @ccrozek. I'm sorry those links weren't current. I've updated the download links in all the classic template READMEs to the latest release code available.
